const checkboxMultipleChoiceQuestions = [
    {
        type: "checkboxMultipleChoice",
        question: "NTO wants to send promotional holiday emails to subscribers who have identified their favorite store locations. Which two actions should NTO take in order to utilize their subscribers’ location preferences? (Choose 2)",
        options: ["A new send classification for holiday promotions", "A From Name for each store location", "A new delivery profile that pulls in store location in the footer", "dynamic From Name that pulls in the store location"],
        
        answer: ["A new delivery profile that pulls in store location in the footer", "dynamic From Name that pulls in the store location"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A marketing manager wants to provide unique content to each customer in an upcoming email campaign. Which three features could be used to create individualized content in the email?",
        options: [  "Dynamic content", 
                    "Einstein content", 
                    "Audience segmentation", 
                    "Personalization strings", 
                    "Specialised content"],
                    
        answer: [   "Dynamic content",
                    "Einstein content", 
                    "Personalization strings"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A local craft store is implementing the Marketing Cloud and will be using Lists to store their subscriber data. Which two types of data can subscribers easily update via the default Profile Center?",
        options: [  "Data Extension Fields", 
                    "List Attributes", 
                    "Order History", 
                    "Email Address"],
                    
        answer: [   "List Attributes", 
                    "Email Address"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A marketer wants to use personalization strings to create individualized content for an upcoming send. What would the marketer need to know to understand how to use personalization strings? (Choose 3)",
        options: [  "Personalization strings can appear in the subject line or body of the email", 
                    "Personalization strings are case sensitive", 
                    "When using subscriber data, the attribute or field should have a default value", 
                    "Personalization strings are noted by two sets of double percent symbols", 
                    "Personalization strings are limited to profile attributes"],
                    
        answer: [   "Personalization strings can appear in the subject line or body of the email",
                    "When using subscriber data, the attribute or field should have a default value", 
                    "Personalization strings are noted by two sets of double percent symbols"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "Distributed a newsletter to alumni, students, faculty, and prospective students. The university’s marketing team wants to see the results of the email campaign. Which two items of information and data about the performance of an individual send can be exported from Tracking in Email Studio? Choose 2 answers",
        options: [  "Number of clicks from mobile devices", 
                    "Images showing how the email rendered on different devices", 
                    "Subscribers who click on a specific link", 
                    "Performance data on the Overview tab"],
                    
        answer: [   "Subscribers who click on a specific link", 
                    "Performance data on the Overview tab"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "Which feature can a marketer use to individualize content in an email? (Choose 3)",
        options: [  "Dynamic content", 
                    "Personalization string", 
                    "Specialized content", 
                    "Audience Segmentation", 
                    "Predictive content"],
                    
        answer: [   "Dynamic content", 
                    "Personalization string", 
                    "Predictive content"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "NTO branding guidelines require heavy use of imagery on its website, app, emails, ads, etc. What two ways that NTO can optimize its email design to honor branding guidelines and ensure subscribers are getting the best experience possible? (Choose 2)",
        options: [  "Style alt text for when images do not display automatically", 
                    "Make the email completely imaged based", 
                    "Add background colors that match branding", 
                    "Use custom corporate font to match the NTO brand"],
                    
        answer: [   "Style alt text for when images do not display automatically", 
                    "Add background colors that match branding"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "NTO is looking at using Journey Builder rather than Automation Studio to send emails. What are the three benefits of using Journey Builder? (Choose 3)",
        options: [  "The ability to setup A/B/N tests as part of the workflow to conduct timing and creative tests", 
                    "The ability to update or create Salesforce CRM objects or records", 
                    "The ability to set goals and have the system listen to see if users met the goal", 
                    "The ability to extract data from an Audience data extension for analysis", 
                    "The ability to set criteria to segment contacts based on behavior using SQL"],
                    
        answer: [   "The ability to setup A/B/N tests as part of the workflow to conduct timing and creative tests", 
                    "The ability to update or create Salesforce CRM objects or records", 
                    "The ability to set goals and have the system listen to see if users met the goal"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A subscriber unsubscribes upon receiving an email from Northern Trail Outfitters (NTO). At the bottom of the NTO email, the subscriber sees three links: Manage Subscriptions, Profile Center, and One-Click Unsubscribe. The subscriber clicks One-Click Unsubscribe. Given that NTO Is using the default subscription center, which two options are given when the subscriber clicks One-Click Unsubscribe? (Choose 2)",
        options: [  "Subscriber can choose to be removed from the data extension.", 
                    "Subscriber can choose to be unsubscribed from all NTO publications.", 
                    "Subscriber can choose which publications to unsubscribe from.", 
                    "Subscriber can choose to resubscrlbe to the list used for the send."],
                    
        answer: [   "Subscriber can choose to be unsubscribed from all NTO publications.", 
                    "Subscriber can choose which publications to unsubscribe from."],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A marketer has been tasked with ensuring Northern Trail Outfitters’ unsubscribe mechanisms are CANSPAM compliant and follow industry best practices.Which two criteria should the marketer incorporate into campaigns to ensure compliance and align with current best practices? Choose 2 answers",
        options: [  "Include an unsubscribe link in the header or footer of emails.", 
                    "Ask the subscriber to log in to the Preference Center to confirm opt-out.", 
                    "Ensure opt-out mechanisms are operational for at least 30 days post-send.", 
                    "Process every individual’s unsubscribe request within 14 business days."],
                    
        answer: [   "Include an unsubscribe link in the header or footer of emails.", 
                    "Ensure opt-out mechanisms are operational for at least 30 days post-send."],
    },
    {
        type: "checkboxMultipleChoice",
        question: "NTO wants its emails to render uniquely between mobile and desktop devices. NTO would like the emails to be responsive. Which two techniques should be used? Choose 2 answers",
        options: [  "Include @media query CSS in the email", 
                    "Use a Basic, Empty or Themed Template in Content Builder", 
                    "Include style=”display:block” on all images", 
                    "Use inline CSS styling on all HTML elements"],
                    
        answer: [   "Include @media query CSS in the email", 
                    "Use a Basic, Empty or Themed Template in Content Builder"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "When deploying a send to its customers, a marketing team would like to  send to its own team members also. However, the team does not want the team members’ open and click behavior to affect the tracking metrics of the send. Which two steps must be completed when creating the data extension to address this need? Choose 2",
        options: [  "Mark the “Is Testable” checkbox", 
                    "Define the Send Relationship by email address", 
                    "Set the Email Address as the Primary Key", 
                    "Mark the “Is Sendable” checkbox"],
                    
        answer: [   "Mark the “Is Testable” checkbox", 
                    "Mark the “Is Sendable” checkbox"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A marketing associate wants to use the Validate button to ensure an email is CAN-SPAM compliant. What information does the associate need to provide in order for the email to pass validation?",
        options: [  "Company Website URL", 
                    "Profile Center URL", 
                    "Terms and Conditions Policy", 
                    "Physical Mailing Address"],
                    
        answer: [   "Profile Center URL", 
                    "Physical Mailing Address"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "A marketer uses Email Approvals. In which send process must an email have an “Approved” status prior to send? (Choose 3)",
        options: [  "Test Sends", 
                    "Send Previews", 
                    "Scheduled Sends", 
                    "Triggered Sends", 
                    "A/B Tests"],
                    
        answer: [   "Scheduled Sends", 
                    "Triggered Sends", 
                    "A/B Tests"],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    },
    {
        type: "checkboxMultipleChoice",
        question: "",
        options: [  "", 
                    "", 
                    "", 
                    ""],
                    
        answer: [   "", 
                    ""],
    }
];
